App\Entity\Room:
    attributes:
        id:
            groups:
                - api:room:create
                - api:room:list
        owner:
            groups:
                - api:room:create
                - api:room:list
