App\Entity\Room:
    attributes:
        id:
            groups:
                - api:room:create
                - api:room:list
        owner:
            groups:
                - api:room:create
                - api:room:list
        opponent:
            groups:
                - api:room:list
        status:
            groups:
                - api:room:list
        isPrivate:
            groups:
                - api:room:list
