App\Entity\User:
    attributes:
        username:
            groups:
                - default
                - api:user:read
                - api:room:create
                - api:room:list
        profilePicturePath:
            groups:
                - api:user:read
                - api:room:list
        inventory:
            groups:
                - api:inventory:read
        userInfo:
            groups:
                - api:user:read
        userWallet:
            groups:
                - api:user:read
        userIdentifier:
            ignore: true
        roles:
            ignore: true
        password:
            ignore: true
        userBadges:
            ignore: true
        decks:
            ignore: true

App\Entity\UserInfo:
    attributes:
        lastBoosterTokensAt:
            groups:
                - api:user:read

App\Entity\UserWallet:
    attributes:
        boosterTokens:
            groups:
                - api:user:read
