<?php

use App\Game\Card;

return [
	'Banana' => Card\BananaCard::class,
	'BananaFarm' => Card\BananaFarmCard::class,
	'Benjamin' => Card\BenjaminCard::class,
	'BloodSucker' => Card\BloodSuckerCard::class,
	'Bomb' => Card\BombCard::class,
	'Isaac' => Card\Character\IsaacCard::class,
	'Necromancian' => Card\Character\NecromancianCard::class,
	'Pierrot' => Card\Character\PierrotCard::class,
	'Stonks' => Card\Character\StonksCard::class,
	'Coins' => Card\CoinsCard::class,
	'Chaos' => Card\ChaosCard::class,
	'Communism' => Card\CommunismCard::class,
	'consolation_prices' => Card\ConsolationPricesCard::class,
	'D6' => Card\D6Card::class,
	'Dart' => Card\DartCard::class,
	'Fortnite' => Card\FortniteCard::class,
	'Gitman' => Card\GitmanCard::class,
	'HackedZone' => Card\HackedZoneCard::class,
	'Horsepill' => Card\HorsepillCard::class,
	'ImStillStanding' => Card\ImStillStandingCard::class,
	'Justice' => Card\JusticeCard::class,
	'MonkeyVillage' => Card\MonkeyVillageCard::class,
	'AlchemistMonkey' => Card\Monster\AlchemistMonkeyCard::class,
	'BFB' => Card\Monster\BFBCard::class,
	'BlackBloon' => Card\Monster\BlackBloonCard::class,
	'BoomerangMonkey' => Card\Monster\BoomerangMonkeyCard::class,
	'CamoBloon' => Card\Monster\CamoBloonCard::class,
	'CeramicBloon' => Card\Monster\CeramicBloonCard::class,
	'Clotty' => Card\Monster\ClottyCard::class,
	'Crypto4Noob' => Card\Monster\Crypto4NoobCard::class,
	'DDT' => Card\Monster\DDTCard::class,
	'DartMonkey' => Card\Monster\DartMonkeyCard::class,
	'GrilledClotty' => Card\Monster\GrilledClottyCard::class,
	'Henry' => Card\Monster\HenryCard::class,
	'HoneyBee' => Card\Monster\HoneyBeeCard::class,
	'LeadBloon' => Card\Monster\LeadBloonCard::class,
	'MOAB' => Card\Monster\MOABCard::class,
	'MechaPainter' => Card\Monster\MechaPainterCard::class,
	'NinjaMonkey' => Card\Monster\NinjaMonkeyCard::class,
	'RadicalRat' => Card\Monster\RadicalRatCard::class,
	'Redbloons' => Card\Monster\RedBloonsMonsterCard::class,
	'SniperMonkey' => Card\Monster\SniperMonkeyCard::class,
	'SuperMonkey' => Card\Monster\SuperMonkeyCard::class,
	'ViciousBee' => Card\Monster\ViciousBeeCard::class,
	'WizardMonkey' => Card\Monster\WizardMonkeyCard::class,
	'Zeppelin' => Card\Monster\ZeppelinCard::class,
	'PierreSaidNoMonsterZone' => Card\PierreSaidNoMonsterZone::class,
	'Pills' => Card\PillsCard::class,
	'Placenta' => Card\PlacentaCard::class,
	'Play2Hurt' => Card\Play2HurtCard::class,
	'RiskyBet' => Card\RiskyBetCard::class,
	'Spicy-D6' => Card\SpicyD6Card::class,
	'StackyStackito' => Card\StackyStackitoCard::class,
	'TheLost' => Card\Monster\TheLostCard::class,
	'TheHand' => Card\TheHandCard::class,
	'ViciousStinger' => Card\ViciousStingerCard::class,
];
