<?php

use App\Game\Card;

return [
	'Benjamin' => Card\BenjaminCard::class,
	'BloodSucker' => Card\BloodSuckerCard::class,
	'Bomb' => Card\BombCard::class,
	'Necromancian' => Card\Character\NecromancianCard::class,
	'Pierrot' => Card\Character\PierrotCard::class,
	'Stonks' => Card\Character\StonksCard::class,
	'Coins' => Card\CoinsCard::class,
	'Communism' => Card\CommunismCard::class,
	'consolation_prices' => Card\ConsolationPricesCard::class,
	'D6' => Card\D6Card::class,
	'Gitman' => Card\GitmanCard::class,
	'Henry' => Card\Monster\HenryCard::class,
	'HackedZone' => Card\HackedZoneCard::class,
	'ImStillStanding' => Card\ImStillStandingCard::class,
	'Justice' => Card\JusticeCard::class,
	'Clotty' => Card\Monster\ClottyCard::class,
	'GrilledClotty' => Card\Monster\GrilledClottyCard::class,
	'Crypto4Noob' => Card\Monster\Crypto4NoobCard::class,
	'MimeticPrismAmethyst' => Card\Monster\MimeticPrismAmethystCard::class,
	'MimeticPrismRuby' => Card\Monster\MimeticPrismRubyCard::class,
	'MimeticPrismSaphir' => Card\Monster\MimeticPrismSaphirCard::class,
	'Redbloons' => Card\Monster\RedBloonsMonsterCard::class,
	'ViciousBee' => Card\Monster\ViciousBeeCard::class,
	'PierreSaidNoMonsterZone' => Card\PierreSaidNoMonsterZone::class,
	'Pillules' => Card\PillsCard::class,
	'Placenta' => Card\PlacentaCard::class,
	'Play2Hurt' => Card\Play2HurtCard::class,
	'RiskyBet' => Card\RiskyBetCard::class,
	'Spicy-D6' => Card\SpicyD6Card::class,
	'StackyStackito' => Card\StackyStackitoCard::class,
	'TheHand' => Card\TheHandCard::class,
	'ViciousStinger' => Card\ViciousStingerCard::class,
];
