# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    app.resources_dir: "%kernel.project_dir%/resources"
    app.cards_list: "%app.resources_dir%/cards_list.php"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Game\Badge\Handler\BadgeHandlerInterface:
            tags: ['app.badge_handler']

    App\:
        resource: '../src/'

    App\Service\BoosterGenerator:
        arguments:
            $cardsListPath: '%app.cards_list%'

    App\Service\BadgeManager:
        arguments:
            $badgeHandlers: !tagged_iterator 'app.badge_handler'

    App\Service\Redis\RedisConnection:
        arguments:
            $redisDsn: '%env(string:REDIS_DSN)%'

when@test:
    services:
        App\Tests\Resources\DoctrineCollector:
            autowire: true
            autoconfigure: true
            public: true

        App\Tests\Resources\InMemoryGameContextRepository:
            autowire: true

        App\Service\Game\GameContextRepositoryInterface: '@App\Tests\Resources\InMemoryGameContextRepository'
