# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    app.resources_dir: "%kernel.project_dir%/resources"
    app.cards_list: "%app.resources_dir%/cards_list.php"
    app.feature_list: "%kernel.project_dir%/config/features.php"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Game'
            - '../src/Debug'
            - '../src/Service/Game'

    App\Utils\KillSwitch:
        arguments:
            $featureList: '%app.feature_list%'

    App\Service\BadgeManager:
        arguments:
            $badgeHandlers: !tagged_iterator 'app.badge_handler'

    App\Service\Redis\RedisConnection:
        arguments:
            $redisDsn: '%env(string:REDIS_DSN)%'

when@test:
    services:
        App\Tests\Resources\DoctrineCollector:
            autowire: true
            autoconfigure: true
            public: true
