parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

when@test:
    services:
        App\Tests\Resources\DoctrineCollector:
            autowire: true
            public: true
            autoconfigure: true
