export const GameEventType = {
  ATTACK: "ATTACK",
  CARD_PLAYED: "CARD_PLAYED",
  CARD_DRAWN: "CARD_DRAWN",
  DAMAGE: "DAMAGE",
  HEAL: "HEAL",
  TURN_ENDED: "TURN_ENDED",
  TURN_STARTED: "TURN_STARTED",
  ROUND_STARTED: "ROUND_STARTED",
  DICE_ROLLED: "DICE_ROLLED",
  CARD_RUNTIME_VALUE: "CARD_RUNTIME_VALUE",
  CARD_DISCARDED: "CARD_DISCARDED",
  EFFECT_ADDED: "EFFECT_ADDED",
  CARD_PLACE_IN_PLAY_AREA: "CARD_PLACE_IN_PLAY_AREA",
  CARD_PLACE_IN_MONSTER_AREA: "CARD_PLACE_IN_MONSTER_AREA",
  UPDATE_CARD_STATE: "UPDATE_CARD_STATE",
  MONSTER_DIED: "MONSTER_DIED",
  CARD_ACTION_PREVENTED: "CARD_ACTION_PREVENTED",
  COINS_GAINED: "COINS_GAINED",
  COINS_LOST: "COINS_LOST",
  CARD_STOLEN: "CARD_STOLEN",
  CARD_REDRAWN: "CARD_REDRAWN",
} as const;

export type GameEventTypeEnum =
  (typeof GameEventType)[keyof typeof GameEventType];
