variant = "loose"

[[issues]]
file = "src/Entity/User.php"
code = "invalid-return-statement"
message = 'Invalid return type for function `app\entity\user::getuseridentifier`: expected `non-empty-string`, but found `string`.'
count = 1

[[issues]]
file = "src/Repository/UserBadgeRepository.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `app\repository\userbadgerepository::findbyuserandbadge`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Service/BoosterGenerator.php"
code = "mixed-return-statement"
message = 'Could not infer a precise return type for function `app\service\boostergenerator::getcardslist`. Saw type `mixed`.'
count = 1

[[issues]]
file = "src/Service/BoosterGenerator.php"
code = "unknown-class-instantiation"
message = "Cannot determine the concrete class for instantiation."
count = 1
