name: Build docker images

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - 'api/**'
      - 'infra/backup/**'

env:
  REGISTRY: ghcr.io
  DOCKER_TARGET: prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        id: vars
        run: |
          REGISTRY_USER=$(echo "Fan2Shrek" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY_USER=$REGISTRY_USER" >> $GITHUB_ENV
          echo "IMAGE_PREFIX=${{ env.REGISTRY }}/$REGISTRY_USER/tcg" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          target: ${{ env.DOCKER_TARGET }}
          tags: ${{ env.IMAGE_PREFIX }}/api:latest
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/api:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/api:buildcache,mode=max
          build-args: |
            PHP_VERSION=8.5.2

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          target: ${{ env.DOCKER_TARGET }}
          tags: ${{ env.IMAGE_PREFIX }}/frontend:latest
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/frontend:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/frontend:buildcache,mode=max
          build-args: |
            API_URL=${{ secrets.API_URL }}
            MERCURE_URL=${{ secrets.MERCURE_URL }}

      - name: Build and push db-backup image
        uses: docker/build-push-action@v6
        with:
          context: ./infra/backup
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/db-backup:latest
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/db-backup:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/db-backup:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to swarm
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: 4892
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PROJECT_PATH }}
            git pull
            make pull
            make networks
            make stack-deploy-backup
            make stack-deploy-infisical
            make stack-deploy
